---
rabbitmq_master_node: "{{ groups['rabbitmq'] | sort | first }}"
rabbitmq_master_nodename: "rabbit@{{ rabbitmq_master_node }}"
rabbitmq_nodename: "rabbit@{{ inventory_hostname }}"

rabbitmq_erlang_packages:
  - erlang-base
  - erlang-asn1
  - erlang-crypto
  - erlang-eldap
  - erlang-ftp
  - erlang-inets
  - erlang-mnesia
  - erlang-os-mon
  - erlang-parsetools
  - erlang-public-key
  - erlang-runtime-tools
  - erlang-snmp
  - erlang-ssl
  - erlang-syntax-tools
  - erlang-tftp
  - erlang-tools
  - erlang-xmerl
