# main.tf — 8 рабочих VM по IPAM (docs/INFRA.md §3): full clone шаблона 9000
# + индивидуальный cloud-init (статический IP, hostname, DNS, timezone,
# SSH-ключ). Ресурсы — жёсткий лимит D8: 2 vCPU / 2048 MiB / 40 GiB.
# agent.wait_for_ip.ipv4=true — apply ждёт, пока qemu-guest-agent сообщит IP
# (встроенная проверка готовности VM).

resource "proxmox_virtual_environment_vm" "node" {
  for_each = local.vms

  node_name   = var.pve_node
  vm_id       = each.value.vmid
  name        = each.key
  description = "kimi-lab ${each.value.group} node ${each.value.ip} (Terraform-managed)"
  tags        = ["kimi-lab", "managed-by-terraform", each.value.group]

  clone {
    vm_id   = proxmox_virtual_environment_vm.ubuntu_template.vm_id
    full    = true
    retries = 2
  }

  agent {
    enabled = true
    timeout = "600s"
    wait_for_ip {
      ipv4 = true
    }
  }

  cpu {
    cores = var.vm_cores
    type  = "host"
  }

  memory {
    dedicated = var.vm_memory_mb
    floating  = 0 # ballooning выключен — RAM фиксирован (D8)
  }

  disk {
    datastore_id = var.pve_storage
    interface    = "scsi0"
    size         = var.vm_disk_gb
  }

  network_device {
    bridge = var.pve_bridge
    model  = "virtio"
  }

  initialization {
    datastore_id = var.pve_storage
    upgrade      = false # без apt-upgrade при первом старте (детерминированность, нет конкуренции за dpkg-lock с Ansible)

    # NOTE: timezone в bpg 0.116 через initialization не задаётся (см.
    # ubuntu-cloudimg.tf «ОГРАНИЧЕНИЕ СТЕНДА»): Europe/Moscow выставляется
    # по SSH после деплоя и поддерживается ролью common (Agent 3).

    user_account {
      username = var.vm_user
      keys     = [trimspace(file(var.ssh_public_key_path))]
    }

    dns {
      servers = var.dns_servers
    }

    ip_config {
      ipv4 {
        address = "${each.value.ip}/${var.netmask}"
        gateway = var.gateway
      }
    }
  }

  serial_device {}

  operating_system {
    type = "l26"
  }

  boot_order = ["scsi0", "net0"]

  on_boot = true
  started = true
}

# Ansible inventory — генерируется из IPAM-карты (local.vms) на каждый apply.
# Файл принадлежит Agent 2; переменные ролей Agent 3/4 кладут в group_vars/,
# а НЕ в этот файл (иначе будут затёрты при следующем apply).
resource "local_file" "ansible_inventory" {
  content = join("\n", compact([
    "---",
    "# GENERATED BY TERRAFORM (Terraform/main.tf local_file.ansible_inventory) — НЕ редактировать вручную!",
    "# Повторный terraform apply перезапишет файл из IPAM-карты Terraform/locals.tf.",
    "# Agent 3/4: переменные групп/хостов добавляйте в Ansible/group_vars/, а не сюда.",
    trimspace(yamlencode(local.inventory)),
    "",
  ]))
  filename        = "${path.module}/../Ansible/inventory/hosts.yml"
  file_permission = "0644"
}
